name: Reformat Java source code

on:
  pull_request:

jobs:
  reformat:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Download Tool
        run: |
          wget -q -O google-java-format.jar \
            https://github.com/google/google-java-format/releases/download/google-java-format-1.9/google-java-format-1.9-all-deps.jar
      - name: Execute formatter
        run: |
          java -jar google-java-format.jar -replace $(git ls-files src/**/*.java)
      - name: Git config
        run: |
          git config --local user.name "yukiusa"
          git config --local user.email "yukiusa@arc-connects.com"
      - name: Git commit
        run: |
          git add -A
          git commit -a -m "[auto action] Reformat Java source code."
          git branch
          echo "${GITHUB_REF#refs/heads/}"
          #git push origin HEAD:${GITHUB_REF#refs/heads/}
