name: Reformat Java source code

on:
  pull_request:

jobs:
  format:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Git settings
        run: |
          # Git リポジトリの設定
          git config --local user.name "yukiusa"
          git config --local user.email "yukiusa@arc-connects.com"
      - name: Code formatter
        run: |
          wget -q -O google-java-format.jar \
            https://github.com/google/google-java-format/releases/download/google-java-format-1.9/google-java-format-1.9-all-deps.jar
          java -jar google-java-format.jar -replace $(git ls-files src/**/*.java)
      - name: Check for modified files
        id: git-check
        run: echo ::set-output name=modified::$(if git diff-index --quiet HEAD --; then echo "false"; else echo "true"; fi)
      - name: Push
        if: steps.git-check.outputs.modified == 'true'
        run: |
          git commit -am "Automated :Reformat Java source code."
          git fetch
          git push -f origin HEAD:${{ github.head_ref }}